Replace calls to "Field::ptr" which is protected with "Field::field_ptr()".
Fix the following issues:
```
error: ‘uchar* Field::ptr’ is protected within this context

error: invalid use of member function ‘uint16 Field::field_index() const’ (did you forget the ‘()’ ?)

error: ‘uint32 Field_varstring::length_bytes’ is private within this context

error: ‘const bool Field_num::unsigned_flag’ is private within this context
```